import { defineConfig } from "tsup";

const config = defineConfig({
  entry: [
    // Main entry points
    "src/index.ts",
    "src/types/index.ts",
    "src/types/trip.ts",
    "src/utils/index.ts",
    "src/utils/cn.ts",
    "src/validation/index.ts",
    "src/helpers/index.ts",
    "src/logger/index.ts",
    "src/themes/index.ts",
    "src/locales/index.ts",
    "src/locales/types.ts",
    "src/locales/pt/index.ts",
    "src/locales/en/index.ts",
    "src/locales/es/index.ts",
    "src/locales/fr/index.ts",
    "src/lib/i18n/index.ts",
    "src/lib/api-client/index.ts",
    "src/contexts/auth/index.ts",
    "src/contexts/auth/AuthContext.tsx",
    "src/contexts/auth/auth-types.ts",
    "src/services/auth-service/index.ts",
    // Additional dependencies
    "src/constants/index.ts",
    "src/config/index.ts",
    "src/config/config.ts",
    "src/factories/index.ts",
    "src/factories/payment.factory.ts",
    // Components - separate entry points
    "src/components/index.ts",
    "src/components/layout/index.ts",
    "src/components/layout/Footer/index.tsx",
    "src/components/layout/Footer/components/BottomSection.tsx",
    "src/components/layout/Footer/components/CompactFooter.tsx",
    "src/components/layout/Footer/components/CompanyInfo.tsx",
    "src/components/layout/Footer/components/FooterBottomSection.tsx",
    "src/components/layout/Footer/components/FooterLinksColumn.tsx",
    "src/components/layout/Footer/components/ModernFooter.tsx",
    "src/components/layout/Footer/components/NewsletterSection.tsx",
    "src/components/layout/Footer/components/PartnershipsSection.tsx",
    "src/components/layout/Footer/components/TraditionalCompanyInfo.tsx",
    "src/components/layout/Footer/components/TraditionalFooterLinksColumn.tsx",
    "src/components/layout/Footer/components/TraditionalPartnershipsSection.tsx",
    "src/components/layout/Footer/data/footerData.ts",
    "src/components/ui/button.tsx",
    "src/components/ui/input.tsx",
    "src/components/common/Logo.tsx",
    "src/components/common/BaseLink.tsx",
    "src/components/auth/index.ts",
    "src/components/auth/LoginForm.tsx",
    "src/components/auth/RegisterForm.tsx",
    "src/components/auth/RegisterFormFields.tsx",
    "src/components/auth/DemoButtons.tsx",
    "src/components/dev/index.ts",
    "src/components/dev/DemoButton.tsx",
    "src/components/GuideCard.tsx",
    "src/components/ContactInfo.tsx",
    "src/components/AvatarUpload.tsx",
    "src/components/Testimonials.tsx",
    "src/components/FeaturedDestinations.tsx",
    "src/components/LanguageSwitcher.tsx",
    "src/components/LanguageSwitcherNextIntl.tsx",
    "src/components/ThemeToggleNextJs.tsx",
    "src/components/common/CustomerSupport/index.ts",
    "src/components/common/ContactForm/index.ts",
    "src/components/common/ImageGallery/index.ts",
    "src/components/common/GridCard/index.ts",
    "src/components/common/ChatBot/index.ts",
    "src/components/common/ErrorBoundary/index.ts",
    "src/components/common/AppHeader/index.ts",
    "src/components/common/Footer/index.ts",
    "src/components/common/BookingWidget/index.ts",
    "src/components/admin/Sidebar/index.tsx",
    "src/components/admin/Sidebar/NavItem.tsx",
    "src/components/admin/Sidebar/SidebarSearch.tsx",
    "src/components/admin/Sidebar/types.ts",
    "src/components/admin/DateRangePicker/index.tsx",
    "src/components/admin/AdminBreadcrumbs/index.tsx",
    "src/components/admin/DashboardCard/index.tsx",
    "src/components/admin/index.ts",
    "src/components/common/UnifiedAI/index.ts",
  ],
  format: ["esm"],
  dts: false,
  sourcemap: true,
  clean: true,
  outDir: "dist",
  bundle: true,
  external: [
    "@akmleva/ui",
    "react",
    "react-dom",
    "framer-motion",
    "lucide-react",
    "react-i18next",
    "i18next",
    "zod",
    "zustand",
    "clsx",
    "tailwind-merge",
    "next-intl",
    "next/navigation",
    "next/router",
    "next/headers",
    "next/image",
    "next/link",
  ],
  splitting: true,
  minify: false,
  platform: "browser",
  target: "es2020",
});

export default config;
