import type { Review, FAQ, Testimonial, PackageService, ServiceProvider, ServiceAvailability, AddOnService } from '../types/package.js';
export declare const createReview: (overrides?: Partial<Review>) => Review;
export declare const createManyReviews: (count: number) => Review[];
export declare const createFAQ: (overrides?: Partial<FAQ>) => FAQ;
export declare const createManyFAQs: (count: number) => FAQ[];
export declare const createTestimonial: (overrides?: Partial<Testimonial>) => Testimonial;
export declare const createManyTestimonials: (count: number) => Testimonial[];
export declare const createServiceProvider: (overrides?: Partial<ServiceProvider>) => ServiceProvider;
export declare const createServiceAvailability: (overrides?: Partial<ServiceAvailability>) => ServiceAvailability;
export declare const createAddOnService: (overrides?: Partial<AddOnService>) => AddOnService;
export declare const createPackageService: (overrides?: Partial<PackageService>) => PackageService;
export declare const createManyPackageServices: (count: number) => PackageService[];
