/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRobotsRouteImport } from './routes/api/robots'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as LegalPageTypeRouteImport } from './routes/legal.$pageType'
import { Route as PreferencesEditRouteImport } from './routes/preferences.edit'
import { Route as PreferencesQuickRouteImport } from './routes/preferences.quick'
import { Route as RoteirosSlugRouteImport } from './routes/roteiros.$slug'
import { Route as ApiAdmin404LogRouteImport } from './routes/api/admin/404-log'
import { Route as ApiAiPreferencesInsightsRouteImport } from './routes/api/ai/preferences-insights'
import { Route as ApiAiRecommendationEventsRouteImport } from './routes/api/ai/recommendation-events'
import { Route as ApiAiRecommendedDestinationsRouteImport } from './routes/api/ai/recommended-destinations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ApiHealthMlStatusRouteImport } from './routes/api/health/ml-status'
import { Route as ApiInternal404LogRouteImport } from './routes/api/internal/404-log'
import { Route as ApiTravelCatalogRouteImport } from './routes/api/travel/catalog'
import { Route as ApiTravelCruisesRouteImport } from './routes/api/travel/cruises'
import { Route as ApiTravelResultsRouteImport } from './routes/api/travel/results'
import { Route as ApiAdminUrlRedirectsIndexRouteImport } from './routes/api/admin/url-redirects/index'
import { Route as ApiAuthMeIndexRouteImport } from './routes/api/auth/me/index'
import { Route as ApiAuthMe2faRouteImport } from './routes/api/auth/me/2fa'
import { Route as ApiAuthMeAvatarRouteImport } from './routes/api/auth/me/avatar'
import { Route as ApiAuthMePasswordRouteImport } from './routes/api/auth/me/password'
import { Route as ApiAuthMeSessionsRouteImport } from './routes/api/auth/me/sessions'
import { Route as ApiAuthVerifyEmailTokenRouteImport } from './routes/api/auth/verify-email.$token'
import { Route as ApiInternalUrlRedirectsIndexRouteImport } from './routes/api/internal/url-redirects/index'
import { Route as ApiTravelV1AisstreamRouteImport } from './routes/api/travel/v1/aisstream'
import { Route as ApiTravelV1CostOfLivingRouteImport } from './routes/api/travel/v1/cost-of-living'
import { Route as ApiTravelV1ListingsRouteImport } from './routes/api/travel/v1/listings'
import { Route as ApiTravelV1NavitiaRouteImport } from './routes/api/travel/v1/navitia'
import { Route as ApiTravelV1RecommendRouteImport } from './routes/api/travel/v1/recommend'
import { Route as ApiTravelV1TransitlandRouteImport } from './routes/api/travel/v1/transitland'
import { Route as ApiTravelV1TransitousRouteImport } from './routes/api/travel/v1/transitous'
import { Route as ApiUserPreferencesIndexRouteImport } from './routes/api/user/preferences/index'
import { Route as ApiUserPreferencesAnalyticsRouteImport } from './routes/api/user/preferences/analytics'
import { Route as ApiUserPreferencesDraftRouteImport } from './routes/api/user/preferences/draft'
import { Route as ApiAdminUrlRedirectsIdVisitRouteImport } from './routes/api/admin/url-redirects/$id/visit'
import { Route as ApiInternalUrlRedirectsIdVisitRouteImport } from './routes/api/internal/url-redirects/$id/visit'
import { Route as ApiTravelV1AccommodationsSearchRouteImport } from './routes/api/travel/v1/accommodations/search'
import { Route as ApiTravelV1DestinationsIndexRouteImport } from './routes/api/travel/v1/destinations/index'
import { Route as ApiTravelV1DestinationsSlugRouteImport } from './routes/api/travel/v1/destinations.$slug'
import { Route as ApiTravelV1DestinationsCountriesRouteImport } from './routes/api/travel/v1/destinations/countries'
import { Route as ApiTravelV1FlightsIndexRouteImport } from './routes/api/travel/v1/flights/index'
import { Route as ApiTravelV1FlightsEstimateRouteImport } from './routes/api/travel/v1/flights/estimate'
import { Route as ApiTravelV1HotelsIndexRouteImport } from './routes/api/travel/v1/hotels/index'
import { Route as ApiTravelV1HotelsIdRouteImport } from './routes/api/travel/v1/hotels/$id'
import { Route as ApiTravelV1HotelsGeocodeRouteImport } from './routes/api/travel/v1/hotels/geocode'
import { Route as ApiTravelV1HotelsNearbyRouteImport } from './routes/api/travel/v1/hotels/nearby'
import { Route as ApiTravelV1HotelsOsmRouteImport } from './routes/api/travel/v1/hotels/osm'
import { Route as ApiTravelV1DestinationsSlugVideosRouteImport } from './routes/api/travel/v1/destinations/$slug/videos'
import { Route as ApiTravelV1HotelsIdImageRouteImport } from './routes/api/travel/v1/hotels/$id/image'
import { Route as ApiTravelV1HotelsIdReviewsRouteImport } from './routes/api/travel/v1/hotels/$id/reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsRoute = ApiRobotsRouteImport.update({
  id: '/api/robots',
  path: '/api/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const LegalPageTypeRoute = LegalPageTypeRouteImport.update({
  id: '/legal/$pageType',
  path: '/legal/$pageType',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesEditRoute = PreferencesEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesQuickRoute = PreferencesQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => PreferencesRoute,
} as any)
const RoteirosSlugRoute = RoteirosSlugRouteImport.update({
  id: '/roteiros/$slug',
  path: '/roteiros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdmin404LogRoute = ApiAdmin404LogRouteImport.update({
  id: '/api/admin/404-log',
  path: '/api/admin/404-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPreferencesInsightsRoute =
  ApiAiPreferencesInsightsRouteImport.update({
    id: '/api/ai/preferences-insights',
    path: '/api/ai/preferences-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiRecommendationEventsRoute =
  ApiAiRecommendationEventsRouteImport.update({
    id: '/api/ai/recommendation-events',
    path: '/api/ai/recommendation-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiRecommendedDestinationsRoute =
  ApiAiRecommendedDestinationsRouteImport.update({
    id: '/api/ai/recommended-destinations',
    path: '/api/ai/recommended-destinations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthMlStatusRoute = ApiHealthMlStatusRouteImport.update({
  id: '/ml-status',
  path: '/ml-status',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiInternal404LogRoute = ApiInternal404LogRouteImport.update({
  id: '/api/internal/404-log',
  path: '/api/internal/404-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelCatalogRoute = ApiTravelCatalogRouteImport.update({
  id: '/api/travel/catalog',
  path: '/api/travel/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelCruisesRoute = ApiTravelCruisesRouteImport.update({
  id: '/api/travel/cruises',
  path: '/api/travel/cruises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelResultsRoute = ApiTravelResultsRouteImport.update({
  id: '/api/travel/results',
  path: '/api/travel/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUrlRedirectsIndexRoute =
  ApiAdminUrlRedirectsIndexRouteImport.update({
    id: '/api/admin/url-redirects/',
    path: '/api/admin/url-redirects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeIndexRoute = ApiAuthMeIndexRouteImport.update({
  id: '/api/auth/me/',
  path: '/api/auth/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMe2faRoute = ApiAuthMe2faRouteImport.update({
  id: '/api/auth/me/2fa',
  path: '/api/auth/me/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeAvatarRoute = ApiAuthMeAvatarRouteImport.update({
  id: '/api/auth/me/avatar',
  path: '/api/auth/me/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMePasswordRoute = ApiAuthMePasswordRouteImport.update({
  id: '/api/auth/me/password',
  path: '/api/auth/me/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeSessionsRoute = ApiAuthMeSessionsRouteImport.update({
  id: '/api/auth/me/sessions',
  path: '/api/auth/me/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailTokenRoute = ApiAuthVerifyEmailTokenRouteImport.update({
  id: '/api/auth/verify-email/$token',
  path: '/api/auth/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalUrlRedirectsIndexRoute =
  ApiInternalUrlRedirectsIndexRouteImport.update({
    id: '/api/internal/url-redirects/',
    path: '/api/internal/url-redirects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1AisstreamRoute = ApiTravelV1AisstreamRouteImport.update({
  id: '/api/travel/v1/aisstream',
  path: '/api/travel/v1/aisstream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1CostOfLivingRoute = ApiTravelV1CostOfLivingRouteImport.update({
  id: '/api/travel/v1/cost-of-living',
  path: '/api/travel/v1/cost-of-living',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1ListingsRoute = ApiTravelV1ListingsRouteImport.update({
  id: '/api/travel/v1/listings',
  path: '/api/travel/v1/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1NavitiaRoute = ApiTravelV1NavitiaRouteImport.update({
  id: '/api/travel/v1/navitia',
  path: '/api/travel/v1/navitia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1RecommendRoute = ApiTravelV1RecommendRouteImport.update({
  id: '/api/travel/v1/recommend',
  path: '/api/travel/v1/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1TransitlandRoute = ApiTravelV1TransitlandRouteImport.update({
  id: '/api/travel/v1/transitland',
  path: '/api/travel/v1/transitland',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1TransitousRoute = ApiTravelV1TransitousRouteImport.update({
  id: '/api/travel/v1/transitous',
  path: '/api/travel/v1/transitous',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesIndexRoute = ApiUserPreferencesIndexRouteImport.update({
  id: '/api/user/preferences/',
  path: '/api/user/preferences/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesAnalyticsRoute =
  ApiUserPreferencesAnalyticsRouteImport.update({
    id: '/api/user/preferences/analytics',
    path: '/api/user/preferences/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserPreferencesDraftRoute = ApiUserPreferencesDraftRouteImport.update({
  id: '/api/user/preferences/draft',
  path: '/api/user/preferences/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUrlRedirectsIdVisitRoute =
  ApiAdminUrlRedirectsIdVisitRouteImport.update({
    id: '/api/admin/url-redirects/$id/visit',
    path: '/api/admin/url-redirects/$id/visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalUrlRedirectsIdVisitRoute =
  ApiInternalUrlRedirectsIdVisitRouteImport.update({
    id: '/api/internal/url-redirects/$id/visit',
    path: '/api/internal/url-redirects/$id/visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1AccommodationsSearchRoute =
  ApiTravelV1AccommodationsSearchRouteImport.update({
    id: '/api/travel/v1/accommodations/search',
    path: '/api/travel/v1/accommodations/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1DestinationsIndexRoute =
  ApiTravelV1DestinationsIndexRouteImport.update({
    id: '/api/travel/v1/destinations/',
    path: '/api/travel/v1/destinations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1DestinationsSlugRoute =
  ApiTravelV1DestinationsSlugRouteImport.update({
    id: '/api/travel/v1/destinations/$slug',
    path: '/api/travel/v1/destinations/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1DestinationsCountriesRoute =
  ApiTravelV1DestinationsCountriesRouteImport.update({
    id: '/api/travel/v1/destinations/countries',
    path: '/api/travel/v1/destinations/countries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1FlightsIndexRoute = ApiTravelV1FlightsIndexRouteImport.update({
  id: '/api/travel/v1/flights/',
  path: '/api/travel/v1/flights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1FlightsEstimateRoute =
  ApiTravelV1FlightsEstimateRouteImport.update({
    id: '/api/travel/v1/flights/estimate',
    path: '/api/travel/v1/flights/estimate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1HotelsIndexRoute = ApiTravelV1HotelsIndexRouteImport.update({
  id: '/api/travel/v1/hotels/',
  path: '/api/travel/v1/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1HotelsIdRoute = ApiTravelV1HotelsIdRouteImport.update({
  id: '/api/travel/v1/hotels/$id',
  path: '/api/travel/v1/hotels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1HotelsGeocodeRoute =
  ApiTravelV1HotelsGeocodeRouteImport.update({
    id: '/api/travel/v1/hotels/geocode',
    path: '/api/travel/v1/hotels/geocode',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1HotelsNearbyRoute = ApiTravelV1HotelsNearbyRouteImport.update({
  id: '/api/travel/v1/hotels/nearby',
  path: '/api/travel/v1/hotels/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1HotelsOsmRoute = ApiTravelV1HotelsOsmRouteImport.update({
  id: '/api/travel/v1/hotels/osm',
  path: '/api/travel/v1/hotels/osm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1DestinationsSlugVideosRoute =
  ApiTravelV1DestinationsSlugVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => ApiTravelV1DestinationsSlugRoute,
  } as any)
const ApiTravelV1HotelsIdImageRoute =
  ApiTravelV1HotelsIdImageRouteImport.update({
    id: '/image',
    path: '/image',
    getParentRoute: () => ApiTravelV1HotelsIdRoute,
  } as any)
const ApiTravelV1HotelsIdReviewsRoute =
  ApiTravelV1HotelsIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => ApiTravelV1HotelsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/admin/404-log': typeof ApiAdmin404LogRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/ai/recommendation-events': typeof ApiAiRecommendationEventsRoute
  '/api/ai/recommended-destinations': typeof ApiAiRecommendedDestinationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/travel/catalog': typeof ApiTravelCatalogRoute
  '/api/travel/cruises': typeof ApiTravelCruisesRoute
  '/api/travel/results': typeof ApiTravelResultsRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/auth/me/2fa': typeof ApiAuthMe2faRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/auth/verify-email/$token': typeof ApiAuthVerifyEmailTokenRoute
  '/api/travel/v1/aisstream': typeof ApiTravelV1AisstreamRoute
  '/api/travel/v1/cost-of-living': typeof ApiTravelV1CostOfLivingRoute
  '/api/travel/v1/listings': typeof ApiTravelV1ListingsRoute
  '/api/travel/v1/navitia': typeof ApiTravelV1NavitiaRoute
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/travel/v1/transitland': typeof ApiTravelV1TransitlandRoute
  '/api/travel/v1/transitous': typeof ApiTravelV1TransitousRoute
  '/api/user/preferences/analytics': typeof ApiUserPreferencesAnalyticsRoute
  '/api/user/preferences/draft': typeof ApiUserPreferencesDraftRoute
  '/api/admin/url-redirects/': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me/': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects/': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences/': typeof ApiUserPreferencesIndexRoute
  '/api/admin/url-redirects/$id/visit': typeof ApiAdminUrlRedirectsIdVisitRoute
  '/api/internal/url-redirects/$id/visit': typeof ApiInternalUrlRedirectsIdVisitRoute
  '/api/travel/v1/accommodations/search': typeof ApiTravelV1AccommodationsSearchRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRouteWithChildren
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/flights/estimate': typeof ApiTravelV1FlightsEstimateRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRouteWithChildren
  '/api/travel/v1/hotels/geocode': typeof ApiTravelV1HotelsGeocodeRoute
  '/api/travel/v1/hotels/nearby': typeof ApiTravelV1HotelsNearbyRoute
  '/api/travel/v1/hotels/osm': typeof ApiTravelV1HotelsOsmRoute
  '/api/travel/v1/destinations/': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights/': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels/': typeof ApiTravelV1HotelsIndexRoute
  '/api/travel/v1/destinations/$slug/videos': typeof ApiTravelV1DestinationsSlugVideosRoute
  '/api/travel/v1/hotels/$id/image': typeof ApiTravelV1HotelsIdImageRoute
  '/api/travel/v1/hotels/$id/reviews': typeof ApiTravelV1HotelsIdReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/admin/404-log': typeof ApiAdmin404LogRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/ai/recommendation-events': typeof ApiAiRecommendationEventsRoute
  '/api/ai/recommended-destinations': typeof ApiAiRecommendedDestinationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/travel/catalog': typeof ApiTravelCatalogRoute
  '/api/travel/cruises': typeof ApiTravelCruisesRoute
  '/api/travel/results': typeof ApiTravelResultsRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/api/auth/me/2fa': typeof ApiAuthMe2faRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/auth/verify-email/$token': typeof ApiAuthVerifyEmailTokenRoute
  '/api/travel/v1/aisstream': typeof ApiTravelV1AisstreamRoute
  '/api/travel/v1/cost-of-living': typeof ApiTravelV1CostOfLivingRoute
  '/api/travel/v1/listings': typeof ApiTravelV1ListingsRoute
  '/api/travel/v1/navitia': typeof ApiTravelV1NavitiaRoute
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/travel/v1/transitland': typeof ApiTravelV1TransitlandRoute
  '/api/travel/v1/transitous': typeof ApiTravelV1TransitousRoute
  '/api/user/preferences/analytics': typeof ApiUserPreferencesAnalyticsRoute
  '/api/user/preferences/draft': typeof ApiUserPreferencesDraftRoute
  '/api/admin/url-redirects': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences': typeof ApiUserPreferencesIndexRoute
  '/api/admin/url-redirects/$id/visit': typeof ApiAdminUrlRedirectsIdVisitRoute
  '/api/internal/url-redirects/$id/visit': typeof ApiInternalUrlRedirectsIdVisitRoute
  '/api/travel/v1/accommodations/search': typeof ApiTravelV1AccommodationsSearchRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRouteWithChildren
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/flights/estimate': typeof ApiTravelV1FlightsEstimateRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRouteWithChildren
  '/api/travel/v1/hotels/geocode': typeof ApiTravelV1HotelsGeocodeRoute
  '/api/travel/v1/hotels/nearby': typeof ApiTravelV1HotelsNearbyRoute
  '/api/travel/v1/hotels/osm': typeof ApiTravelV1HotelsOsmRoute
  '/api/travel/v1/destinations': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels': typeof ApiTravelV1HotelsIndexRoute
  '/api/travel/v1/destinations/$slug/videos': typeof ApiTravelV1DestinationsSlugVideosRoute
  '/api/travel/v1/hotels/$id/image': typeof ApiTravelV1HotelsIdImageRoute
  '/api/travel/v1/hotels/$id/reviews': typeof ApiTravelV1HotelsIdReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/admin/404-log': typeof ApiAdmin404LogRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/ai/recommendation-events': typeof ApiAiRecommendationEventsRoute
  '/api/ai/recommended-destinations': typeof ApiAiRecommendedDestinationsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/travel/catalog': typeof ApiTravelCatalogRoute
  '/api/travel/cruises': typeof ApiTravelCruisesRoute
  '/api/travel/results': typeof ApiTravelResultsRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/auth/me/2fa': typeof ApiAuthMe2faRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/auth/verify-email/$token': typeof ApiAuthVerifyEmailTokenRoute
  '/api/travel/v1/aisstream': typeof ApiTravelV1AisstreamRoute
  '/api/travel/v1/cost-of-living': typeof ApiTravelV1CostOfLivingRoute
  '/api/travel/v1/listings': typeof ApiTravelV1ListingsRoute
  '/api/travel/v1/navitia': typeof ApiTravelV1NavitiaRoute
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/travel/v1/transitland': typeof ApiTravelV1TransitlandRoute
  '/api/travel/v1/transitous': typeof ApiTravelV1TransitousRoute
  '/api/user/preferences/analytics': typeof ApiUserPreferencesAnalyticsRoute
  '/api/user/preferences/draft': typeof ApiUserPreferencesDraftRoute
  '/api/admin/url-redirects/': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me/': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects/': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences/': typeof ApiUserPreferencesIndexRoute
  '/api/admin/url-redirects/$id/visit': typeof ApiAdminUrlRedirectsIdVisitRoute
  '/api/internal/url-redirects/$id/visit': typeof ApiInternalUrlRedirectsIdVisitRoute
  '/api/travel/v1/accommodations/search': typeof ApiTravelV1AccommodationsSearchRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRouteWithChildren
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/flights/estimate': typeof ApiTravelV1FlightsEstimateRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRouteWithChildren
  '/api/travel/v1/hotels/geocode': typeof ApiTravelV1HotelsGeocodeRoute
  '/api/travel/v1/hotels/nearby': typeof ApiTravelV1HotelsNearbyRoute
  '/api/travel/v1/hotels/osm': typeof ApiTravelV1HotelsOsmRoute
  '/api/travel/v1/destinations/': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights/': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels/': typeof ApiTravelV1HotelsIndexRoute
  '/api/travel/v1/destinations/$slug/videos': typeof ApiTravelV1DestinationsSlugVideosRoute
  '/api/travel/v1/hotels/$id/image': typeof ApiTravelV1HotelsIdImageRoute
  '/api/travel/v1/hotels/$id/reviews': typeof ApiTravelV1HotelsIdReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/csp-report'
    | '/api/health'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/admin/404-log'
    | '/api/ai/preferences-insights'
    | '/api/ai/recommendation-events'
    | '/api/ai/recommended-destinations'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/travel/catalog'
    | '/api/travel/cruises'
    | '/api/travel/results'
    | '/api/health/'
    | '/api/auth/me/2fa'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/auth/verify-email/$token'
    | '/api/travel/v1/aisstream'
    | '/api/travel/v1/cost-of-living'
    | '/api/travel/v1/listings'
    | '/api/travel/v1/navitia'
    | '/api/travel/v1/recommend'
    | '/api/travel/v1/transitland'
    | '/api/travel/v1/transitous'
    | '/api/user/preferences/analytics'
    | '/api/user/preferences/draft'
    | '/api/admin/url-redirects/'
    | '/api/auth/me/'
    | '/api/internal/url-redirects/'
    | '/api/user/preferences/'
    | '/api/admin/url-redirects/$id/visit'
    | '/api/internal/url-redirects/$id/visit'
    | '/api/travel/v1/accommodations/search'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/flights/estimate'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/hotels/geocode'
    | '/api/travel/v1/hotels/nearby'
    | '/api/travel/v1/hotels/osm'
    | '/api/travel/v1/destinations/'
    | '/api/travel/v1/flights/'
    | '/api/travel/v1/hotels/'
    | '/api/travel/v1/destinations/$slug/videos'
    | '/api/travel/v1/hotels/$id/image'
    | '/api/travel/v1/hotels/$id/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/csp-report'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/admin/404-log'
    | '/api/ai/preferences-insights'
    | '/api/ai/recommendation-events'
    | '/api/ai/recommended-destinations'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/travel/catalog'
    | '/api/travel/cruises'
    | '/api/travel/results'
    | '/api/health'
    | '/api/auth/me/2fa'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/auth/verify-email/$token'
    | '/api/travel/v1/aisstream'
    | '/api/travel/v1/cost-of-living'
    | '/api/travel/v1/listings'
    | '/api/travel/v1/navitia'
    | '/api/travel/v1/recommend'
    | '/api/travel/v1/transitland'
    | '/api/travel/v1/transitous'
    | '/api/user/preferences/analytics'
    | '/api/user/preferences/draft'
    | '/api/admin/url-redirects'
    | '/api/auth/me'
    | '/api/internal/url-redirects'
    | '/api/user/preferences'
    | '/api/admin/url-redirects/$id/visit'
    | '/api/internal/url-redirects/$id/visit'
    | '/api/travel/v1/accommodations/search'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/flights/estimate'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/hotels/geocode'
    | '/api/travel/v1/hotels/nearby'
    | '/api/travel/v1/hotels/osm'
    | '/api/travel/v1/destinations'
    | '/api/travel/v1/flights'
    | '/api/travel/v1/hotels'
    | '/api/travel/v1/destinations/$slug/videos'
    | '/api/travel/v1/hotels/$id/image'
    | '/api/travel/v1/hotels/$id/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/csp-report'
    | '/api/health'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/admin/404-log'
    | '/api/ai/preferences-insights'
    | '/api/ai/recommendation-events'
    | '/api/ai/recommended-destinations'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/travel/catalog'
    | '/api/travel/cruises'
    | '/api/travel/results'
    | '/api/health/'
    | '/api/auth/me/2fa'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/auth/verify-email/$token'
    | '/api/travel/v1/aisstream'
    | '/api/travel/v1/cost-of-living'
    | '/api/travel/v1/listings'
    | '/api/travel/v1/navitia'
    | '/api/travel/v1/recommend'
    | '/api/travel/v1/transitland'
    | '/api/travel/v1/transitous'
    | '/api/user/preferences/analytics'
    | '/api/user/preferences/draft'
    | '/api/admin/url-redirects/'
    | '/api/auth/me/'
    | '/api/internal/url-redirects/'
    | '/api/user/preferences/'
    | '/api/admin/url-redirects/$id/visit'
    | '/api/internal/url-redirects/$id/visit'
    | '/api/travel/v1/accommodations/search'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/flights/estimate'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/hotels/geocode'
    | '/api/travel/v1/hotels/nearby'
    | '/api/travel/v1/hotels/osm'
    | '/api/travel/v1/destinations/'
    | '/api/travel/v1/flights/'
    | '/api/travel/v1/hotels/'
    | '/api/travel/v1/destinations/$slug/videos'
    | '/api/travel/v1/hotels/$id/image'
    | '/api/travel/v1/hotels/$id/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PreferencesRoute: typeof PreferencesRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiRobotsRoute: typeof ApiRobotsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  LegalPageTypeRoute: typeof LegalPageTypeRoute
  RoteirosSlugRoute: typeof RoteirosSlugRoute
  ApiAdmin404LogRoute: typeof ApiAdmin404LogRoute
  ApiAiPreferencesInsightsRoute: typeof ApiAiPreferencesInsightsRoute
  ApiAiRecommendationEventsRoute: typeof ApiAiRecommendationEventsRoute
  ApiAiRecommendedDestinationsRoute: typeof ApiAiRecommendedDestinationsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiInternal404LogRoute: typeof ApiInternal404LogRoute
  ApiTravelCatalogRoute: typeof ApiTravelCatalogRoute
  ApiTravelCruisesRoute: typeof ApiTravelCruisesRoute
  ApiTravelResultsRoute: typeof ApiTravelResultsRoute
  ApiAuthMe2faRoute: typeof ApiAuthMe2faRoute
  ApiAuthMeAvatarRoute: typeof ApiAuthMeAvatarRoute
  ApiAuthMePasswordRoute: typeof ApiAuthMePasswordRoute
  ApiAuthMeSessionsRoute: typeof ApiAuthMeSessionsRoute
  ApiAuthVerifyEmailTokenRoute: typeof ApiAuthVerifyEmailTokenRoute
  ApiTravelV1AisstreamRoute: typeof ApiTravelV1AisstreamRoute
  ApiTravelV1CostOfLivingRoute: typeof ApiTravelV1CostOfLivingRoute
  ApiTravelV1ListingsRoute: typeof ApiTravelV1ListingsRoute
  ApiTravelV1NavitiaRoute: typeof ApiTravelV1NavitiaRoute
  ApiTravelV1RecommendRoute: typeof ApiTravelV1RecommendRoute
  ApiTravelV1TransitlandRoute: typeof ApiTravelV1TransitlandRoute
  ApiTravelV1TransitousRoute: typeof ApiTravelV1TransitousRoute
  ApiUserPreferencesAnalyticsRoute: typeof ApiUserPreferencesAnalyticsRoute
  ApiUserPreferencesDraftRoute: typeof ApiUserPreferencesDraftRoute
  ApiAdminUrlRedirectsIndexRoute: typeof ApiAdminUrlRedirectsIndexRoute
  ApiAuthMeIndexRoute: typeof ApiAuthMeIndexRoute
  ApiInternalUrlRedirectsIndexRoute: typeof ApiInternalUrlRedirectsIndexRoute
  ApiUserPreferencesIndexRoute: typeof ApiUserPreferencesIndexRoute
  ApiAdminUrlRedirectsIdVisitRoute: typeof ApiAdminUrlRedirectsIdVisitRoute
  ApiInternalUrlRedirectsIdVisitRoute: typeof ApiInternalUrlRedirectsIdVisitRoute
  ApiTravelV1AccommodationsSearchRoute: typeof ApiTravelV1AccommodationsSearchRoute
  ApiTravelV1DestinationsSlugRoute: typeof ApiTravelV1DestinationsSlugRouteWithChildren
  ApiTravelV1DestinationsCountriesRoute: typeof ApiTravelV1DestinationsCountriesRoute
  ApiTravelV1FlightsEstimateRoute: typeof ApiTravelV1FlightsEstimateRoute
  ApiTravelV1HotelsIdRoute: typeof ApiTravelV1HotelsIdRouteWithChildren
  ApiTravelV1HotelsGeocodeRoute: typeof ApiTravelV1HotelsGeocodeRoute
  ApiTravelV1HotelsNearbyRoute: typeof ApiTravelV1HotelsNearbyRoute
  ApiTravelV1HotelsOsmRoute: typeof ApiTravelV1HotelsOsmRoute
  ApiTravelV1DestinationsIndexRoute: typeof ApiTravelV1DestinationsIndexRoute
  ApiTravelV1FlightsIndexRoute: typeof ApiTravelV1FlightsIndexRoute
  ApiTravelV1HotelsIndexRoute: typeof ApiTravelV1HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots': {
      id: '/api/robots'
      path: '/api/robots'
      fullPath: '/api/robots'
      preLoaderRoute: typeof ApiRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/legal/$pageType': {
      id: '/legal/$pageType'
      path: '/legal/$pageType'
      fullPath: '/legal/$pageType'
      preLoaderRoute: typeof LegalPageTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/edit': {
      id: '/preferences/edit'
      path: '/edit'
      fullPath: '/preferences/edit'
      preLoaderRoute: typeof PreferencesEditRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/quick': {
      id: '/preferences/quick'
      path: '/quick'
      fullPath: '/preferences/quick'
      preLoaderRoute: typeof PreferencesQuickRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/roteiros/$slug': {
      id: '/roteiros/$slug'
      path: '/roteiros/$slug'
      fullPath: '/roteiros/$slug'
      preLoaderRoute: typeof RoteirosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/404-log': {
      id: '/api/admin/404-log'
      path: '/api/admin/404-log'
      fullPath: '/api/admin/404-log'
      preLoaderRoute: typeof ApiAdmin404LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/preferences-insights': {
      id: '/api/ai/preferences-insights'
      path: '/api/ai/preferences-insights'
      fullPath: '/api/ai/preferences-insights'
      preLoaderRoute: typeof ApiAiPreferencesInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/recommendation-events': {
      id: '/api/ai/recommendation-events'
      path: '/api/ai/recommendation-events'
      fullPath: '/api/ai/recommendation-events'
      preLoaderRoute: typeof ApiAiRecommendationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/recommended-destinations': {
      id: '/api/ai/recommended-destinations'
      path: '/api/ai/recommended-destinations'
      fullPath: '/api/ai/recommended-destinations'
      preLoaderRoute: typeof ApiAiRecommendedDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ml-status': {
      id: '/api/health/ml-status'
      path: '/ml-status'
      fullPath: '/api/health/ml-status'
      preLoaderRoute: typeof ApiHealthMlStatusRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/internal/404-log': {
      id: '/api/internal/404-log'
      path: '/api/internal/404-log'
      fullPath: '/api/internal/404-log'
      preLoaderRoute: typeof ApiInternal404LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/catalog': {
      id: '/api/travel/catalog'
      path: '/api/travel/catalog'
      fullPath: '/api/travel/catalog'
      preLoaderRoute: typeof ApiTravelCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/cruises': {
      id: '/api/travel/cruises'
      path: '/api/travel/cruises'
      fullPath: '/api/travel/cruises'
      preLoaderRoute: typeof ApiTravelCruisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/results': {
      id: '/api/travel/results'
      path: '/api/travel/results'
      fullPath: '/api/travel/results'
      preLoaderRoute: typeof ApiTravelResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/url-redirects/': {
      id: '/api/admin/url-redirects/'
      path: '/api/admin/url-redirects'
      fullPath: '/api/admin/url-redirects/'
      preLoaderRoute: typeof ApiAdminUrlRedirectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/': {
      id: '/api/auth/me/'
      path: '/api/auth/me'
      fullPath: '/api/auth/me/'
      preLoaderRoute: typeof ApiAuthMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/2fa': {
      id: '/api/auth/me/2fa'
      path: '/api/auth/me/2fa'
      fullPath: '/api/auth/me/2fa'
      preLoaderRoute: typeof ApiAuthMe2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/avatar': {
      id: '/api/auth/me/avatar'
      path: '/api/auth/me/avatar'
      fullPath: '/api/auth/me/avatar'
      preLoaderRoute: typeof ApiAuthMeAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/password': {
      id: '/api/auth/me/password'
      path: '/api/auth/me/password'
      fullPath: '/api/auth/me/password'
      preLoaderRoute: typeof ApiAuthMePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/sessions': {
      id: '/api/auth/me/sessions'
      path: '/api/auth/me/sessions'
      fullPath: '/api/auth/me/sessions'
      preLoaderRoute: typeof ApiAuthMeSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email/$token': {
      id: '/api/auth/verify-email/$token'
      path: '/api/auth/verify-email/$token'
      fullPath: '/api/auth/verify-email/$token'
      preLoaderRoute: typeof ApiAuthVerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/url-redirects/': {
      id: '/api/internal/url-redirects/'
      path: '/api/internal/url-redirects'
      fullPath: '/api/internal/url-redirects/'
      preLoaderRoute: typeof ApiInternalUrlRedirectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/aisstream': {
      id: '/api/travel/v1/aisstream'
      path: '/api/travel/v1/aisstream'
      fullPath: '/api/travel/v1/aisstream'
      preLoaderRoute: typeof ApiTravelV1AisstreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/cost-of-living': {
      id: '/api/travel/v1/cost-of-living'
      path: '/api/travel/v1/cost-of-living'
      fullPath: '/api/travel/v1/cost-of-living'
      preLoaderRoute: typeof ApiTravelV1CostOfLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/listings': {
      id: '/api/travel/v1/listings'
      path: '/api/travel/v1/listings'
      fullPath: '/api/travel/v1/listings'
      preLoaderRoute: typeof ApiTravelV1ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/navitia': {
      id: '/api/travel/v1/navitia'
      path: '/api/travel/v1/navitia'
      fullPath: '/api/travel/v1/navitia'
      preLoaderRoute: typeof ApiTravelV1NavitiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/recommend': {
      id: '/api/travel/v1/recommend'
      path: '/api/travel/v1/recommend'
      fullPath: '/api/travel/v1/recommend'
      preLoaderRoute: typeof ApiTravelV1RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/transitland': {
      id: '/api/travel/v1/transitland'
      path: '/api/travel/v1/transitland'
      fullPath: '/api/travel/v1/transitland'
      preLoaderRoute: typeof ApiTravelV1TransitlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/transitous': {
      id: '/api/travel/v1/transitous'
      path: '/api/travel/v1/transitous'
      fullPath: '/api/travel/v1/transitous'
      preLoaderRoute: typeof ApiTravelV1TransitousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences/': {
      id: '/api/user/preferences/'
      path: '/api/user/preferences'
      fullPath: '/api/user/preferences/'
      preLoaderRoute: typeof ApiUserPreferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences/analytics': {
      id: '/api/user/preferences/analytics'
      path: '/api/user/preferences/analytics'
      fullPath: '/api/user/preferences/analytics'
      preLoaderRoute: typeof ApiUserPreferencesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences/draft': {
      id: '/api/user/preferences/draft'
      path: '/api/user/preferences/draft'
      fullPath: '/api/user/preferences/draft'
      preLoaderRoute: typeof ApiUserPreferencesDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/url-redirects/$id/visit': {
      id: '/api/admin/url-redirects/$id/visit'
      path: '/api/admin/url-redirects/$id/visit'
      fullPath: '/api/admin/url-redirects/$id/visit'
      preLoaderRoute: typeof ApiAdminUrlRedirectsIdVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/url-redirects/$id/visit': {
      id: '/api/internal/url-redirects/$id/visit'
      path: '/api/internal/url-redirects/$id/visit'
      fullPath: '/api/internal/url-redirects/$id/visit'
      preLoaderRoute: typeof ApiInternalUrlRedirectsIdVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/accommodations/search': {
      id: '/api/travel/v1/accommodations/search'
      path: '/api/travel/v1/accommodations/search'
      fullPath: '/api/travel/v1/accommodations/search'
      preLoaderRoute: typeof ApiTravelV1AccommodationsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/destinations/': {
      id: '/api/travel/v1/destinations/'
      path: '/api/travel/v1/destinations'
      fullPath: '/api/travel/v1/destinations/'
      preLoaderRoute: typeof ApiTravelV1DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/destinations/$slug': {
      id: '/api/travel/v1/destinations/$slug'
      path: '/api/travel/v1/destinations/$slug'
      fullPath: '/api/travel/v1/destinations/$slug'
      preLoaderRoute: typeof ApiTravelV1DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/destinations/countries': {
      id: '/api/travel/v1/destinations/countries'
      path: '/api/travel/v1/destinations/countries'
      fullPath: '/api/travel/v1/destinations/countries'
      preLoaderRoute: typeof ApiTravelV1DestinationsCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/flights/': {
      id: '/api/travel/v1/flights/'
      path: '/api/travel/v1/flights'
      fullPath: '/api/travel/v1/flights/'
      preLoaderRoute: typeof ApiTravelV1FlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/flights/estimate': {
      id: '/api/travel/v1/flights/estimate'
      path: '/api/travel/v1/flights/estimate'
      fullPath: '/api/travel/v1/flights/estimate'
      preLoaderRoute: typeof ApiTravelV1FlightsEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels/': {
      id: '/api/travel/v1/hotels/'
      path: '/api/travel/v1/hotels'
      fullPath: '/api/travel/v1/hotels/'
      preLoaderRoute: typeof ApiTravelV1HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels/$id': {
      id: '/api/travel/v1/hotels/$id'
      path: '/api/travel/v1/hotels/$id'
      fullPath: '/api/travel/v1/hotels/$id'
      preLoaderRoute: typeof ApiTravelV1HotelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels/geocode': {
      id: '/api/travel/v1/hotels/geocode'
      path: '/api/travel/v1/hotels/geocode'
      fullPath: '/api/travel/v1/hotels/geocode'
      preLoaderRoute: typeof ApiTravelV1HotelsGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels/nearby': {
      id: '/api/travel/v1/hotels/nearby'
      path: '/api/travel/v1/hotels/nearby'
      fullPath: '/api/travel/v1/hotels/nearby'
      preLoaderRoute: typeof ApiTravelV1HotelsNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels/osm': {
      id: '/api/travel/v1/hotels/osm'
      path: '/api/travel/v1/hotels/osm'
      fullPath: '/api/travel/v1/hotels/osm'
      preLoaderRoute: typeof ApiTravelV1HotelsOsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/destinations/$slug/videos': {
      id: '/api/travel/v1/destinations/$slug/videos'
      path: '/videos'
      fullPath: '/api/travel/v1/destinations/$slug/videos'
      preLoaderRoute: typeof ApiTravelV1DestinationsSlugVideosRouteImport
      parentRoute: typeof ApiTravelV1DestinationsSlugRoute
    }
    '/api/travel/v1/hotels/$id/image': {
      id: '/api/travel/v1/hotels/$id/image'
      path: '/image'
      fullPath: '/api/travel/v1/hotels/$id/image'
      preLoaderRoute: typeof ApiTravelV1HotelsIdImageRouteImport
      parentRoute: typeof ApiTravelV1HotelsIdRoute
    }
    '/api/travel/v1/hotels/$id/reviews': {
      id: '/api/travel/v1/hotels/$id/reviews'
      path: '/reviews'
      fullPath: '/api/travel/v1/hotels/$id/reviews'
      preLoaderRoute: typeof ApiTravelV1HotelsIdReviewsRouteImport
      parentRoute: typeof ApiTravelV1HotelsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PreferencesRouteChildren {
  PreferencesEditRoute: typeof PreferencesEditRoute
  PreferencesQuickRoute: typeof PreferencesQuickRoute
}

const PreferencesRouteChildren: PreferencesRouteChildren = {
  PreferencesEditRoute: PreferencesEditRoute,
  PreferencesQuickRoute: PreferencesQuickRoute,
}

const PreferencesRouteWithChildren = PreferencesRoute._addFileChildren(
  PreferencesRouteChildren,
)

interface ApiHealthRouteChildren {
  ApiHealthMlStatusRoute: typeof ApiHealthMlStatusRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthMlStatusRoute: ApiHealthMlStatusRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiTravelV1DestinationsSlugRouteChildren {
  ApiTravelV1DestinationsSlugVideosRoute: typeof ApiTravelV1DestinationsSlugVideosRoute
}

const ApiTravelV1DestinationsSlugRouteChildren: ApiTravelV1DestinationsSlugRouteChildren =
  {
    ApiTravelV1DestinationsSlugVideosRoute:
      ApiTravelV1DestinationsSlugVideosRoute,
  }

const ApiTravelV1DestinationsSlugRouteWithChildren =
  ApiTravelV1DestinationsSlugRoute._addFileChildren(
    ApiTravelV1DestinationsSlugRouteChildren,
  )

interface ApiTravelV1HotelsIdRouteChildren {
  ApiTravelV1HotelsIdImageRoute: typeof ApiTravelV1HotelsIdImageRoute
  ApiTravelV1HotelsIdReviewsRoute: typeof ApiTravelV1HotelsIdReviewsRoute
}

const ApiTravelV1HotelsIdRouteChildren: ApiTravelV1HotelsIdRouteChildren = {
  ApiTravelV1HotelsIdImageRoute: ApiTravelV1HotelsIdImageRoute,
  ApiTravelV1HotelsIdReviewsRoute: ApiTravelV1HotelsIdReviewsRoute,
}

const ApiTravelV1HotelsIdRouteWithChildren =
  ApiTravelV1HotelsIdRoute._addFileChildren(ApiTravelV1HotelsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PreferencesRoute: PreferencesRouteWithChildren,
  ResultsRoute: ResultsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiRobotsRoute: ApiRobotsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  LegalPageTypeRoute: LegalPageTypeRoute,
  RoteirosSlugRoute: RoteirosSlugRoute,
  ApiAdmin404LogRoute: ApiAdmin404LogRoute,
  ApiAiPreferencesInsightsRoute: ApiAiPreferencesInsightsRoute,
  ApiAiRecommendationEventsRoute: ApiAiRecommendationEventsRoute,
  ApiAiRecommendedDestinationsRoute: ApiAiRecommendedDestinationsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiInternal404LogRoute: ApiInternal404LogRoute,
  ApiTravelCatalogRoute: ApiTravelCatalogRoute,
  ApiTravelCruisesRoute: ApiTravelCruisesRoute,
  ApiTravelResultsRoute: ApiTravelResultsRoute,
  ApiAuthMe2faRoute: ApiAuthMe2faRoute,
  ApiAuthMeAvatarRoute: ApiAuthMeAvatarRoute,
  ApiAuthMePasswordRoute: ApiAuthMePasswordRoute,
  ApiAuthMeSessionsRoute: ApiAuthMeSessionsRoute,
  ApiAuthVerifyEmailTokenRoute: ApiAuthVerifyEmailTokenRoute,
  ApiTravelV1AisstreamRoute: ApiTravelV1AisstreamRoute,
  ApiTravelV1CostOfLivingRoute: ApiTravelV1CostOfLivingRoute,
  ApiTravelV1ListingsRoute: ApiTravelV1ListingsRoute,
  ApiTravelV1NavitiaRoute: ApiTravelV1NavitiaRoute,
  ApiTravelV1RecommendRoute: ApiTravelV1RecommendRoute,
  ApiTravelV1TransitlandRoute: ApiTravelV1TransitlandRoute,
  ApiTravelV1TransitousRoute: ApiTravelV1TransitousRoute,
  ApiUserPreferencesAnalyticsRoute: ApiUserPreferencesAnalyticsRoute,
  ApiUserPreferencesDraftRoute: ApiUserPreferencesDraftRoute,
  ApiAdminUrlRedirectsIndexRoute: ApiAdminUrlRedirectsIndexRoute,
  ApiAuthMeIndexRoute: ApiAuthMeIndexRoute,
  ApiInternalUrlRedirectsIndexRoute: ApiInternalUrlRedirectsIndexRoute,
  ApiUserPreferencesIndexRoute: ApiUserPreferencesIndexRoute,
  ApiAdminUrlRedirectsIdVisitRoute: ApiAdminUrlRedirectsIdVisitRoute,
  ApiInternalUrlRedirectsIdVisitRoute: ApiInternalUrlRedirectsIdVisitRoute,
  ApiTravelV1AccommodationsSearchRoute: ApiTravelV1AccommodationsSearchRoute,
  ApiTravelV1DestinationsSlugRoute:
    ApiTravelV1DestinationsSlugRouteWithChildren,
  ApiTravelV1DestinationsCountriesRoute: ApiTravelV1DestinationsCountriesRoute,
  ApiTravelV1FlightsEstimateRoute: ApiTravelV1FlightsEstimateRoute,
  ApiTravelV1HotelsIdRoute: ApiTravelV1HotelsIdRouteWithChildren,
  ApiTravelV1HotelsGeocodeRoute: ApiTravelV1HotelsGeocodeRoute,
  ApiTravelV1HotelsNearbyRoute: ApiTravelV1HotelsNearbyRoute,
  ApiTravelV1HotelsOsmRoute: ApiTravelV1HotelsOsmRoute,
  ApiTravelV1DestinationsIndexRoute: ApiTravelV1DestinationsIndexRoute,
  ApiTravelV1FlightsIndexRoute: ApiTravelV1FlightsIndexRoute,
  ApiTravelV1HotelsIndexRoute: ApiTravelV1HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
