/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRobotsRouteImport } from './routes/api/robots'
import { Route as ApiSitemapRouteImport } from './routes/api/sitemap'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as LegalPageTypeRouteImport } from './routes/legal.$pageType'
import { Route as PreferencesEditRouteImport } from './routes/preferences.edit'
import { Route as PreferencesQuickRouteImport } from './routes/preferences.quick'
import { Route as RoteirosSlugRouteImport } from './routes/roteiros.$slug'
import { Route as ApiAiPreferencesInsightsRouteImport } from './routes/api/ai/preferences-insights'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ApiHealthMlStatusRouteImport } from './routes/api/health/ml-status'
import { Route as ApiInternal404LogRouteImport } from './routes/api/internal/404-log'
import { Route as ApiUserPreferencesRouteImport } from './routes/api/user/preferences'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAdminUrlRedirectsIndexRouteImport } from './routes/api/admin/url-redirects/index'
import { Route as ApiAuthMeIndexRouteImport } from './routes/api/auth/me/index'
import { Route as ApiAuthMeAvatarRouteImport } from './routes/api/auth/me/avatar'
import { Route as ApiAuthMePasswordRouteImport } from './routes/api/auth/me/password'
import { Route as ApiAuthMeSessionsRouteImport } from './routes/api/auth/me/sessions'
import { Route as ApiInternalUrlRedirectsIndexRouteImport } from './routes/api/internal/url-redirects/index'
import { Route as ApiTravelV1DestinationsRouteImport } from './routes/api/travel/v1/destinations'
import { Route as ApiTravelV1FlightsRouteImport } from './routes/api/travel/v1/flights'
import { Route as ApiTravelV1HotelsRouteImport } from './routes/api/travel/v1/hotels'
import { Route as ApiTravelV1RecommendRouteImport } from './routes/api/travel/v1/recommend'
import { Route as ApiUserPreferencesIndexRouteImport } from './routes/api/user/preferences/index'
import { Route as ApiTravelV1DestinationsIndexRouteImport } from './routes/api/travel/v1/destinations/index'
import { Route as ApiTravelV1DestinationsSlugRouteImport } from './routes/api/travel/v1/destinations.$slug'
import { Route as ApiTravelV1DestinationsCountriesRouteImport } from './routes/api/travel/v1/destinations/countries'
import { Route as ApiTravelV1FlightsIndexRouteImport } from './routes/api/travel/v1/flights/index'
import { Route as ApiTravelV1HotelsIndexRouteImport } from './routes/api/travel/v1/hotels/index'
import { Route as ApiTravelV1HotelsIdRouteImport } from './routes/api/travel/v1/hotels/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsRoute = ApiRobotsRouteImport.update({
  id: '/api/robots',
  path: '/api/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapRoute = ApiSitemapRouteImport.update({
  id: '/api/sitemap',
  path: '/api/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const LegalPageTypeRoute = LegalPageTypeRouteImport.update({
  id: '/legal/$pageType',
  path: '/legal/$pageType',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesEditRoute = PreferencesEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PreferencesRoute,
} as any)
const PreferencesQuickRoute = PreferencesQuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => PreferencesRoute,
} as any)
const RoteirosSlugRoute = RoteirosSlugRouteImport.update({
  id: '/roteiros/$slug',
  path: '/roteiros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPreferencesInsightsRoute =
  ApiAiPreferencesInsightsRouteImport.update({
    id: '/api/ai/preferences-insights',
    path: '/api/ai/preferences-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthMlStatusRoute = ApiHealthMlStatusRouteImport.update({
  id: '/ml-status',
  path: '/ml-status',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiInternal404LogRoute = ApiInternal404LogRouteImport.update({
  id: '/api/internal/404-log',
  path: '/api/internal/404-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesRoute = ApiUserPreferencesRouteImport.update({
  id: '/api/user/preferences',
  path: '/api/user/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUrlRedirectsIndexRoute =
  ApiAdminUrlRedirectsIndexRouteImport.update({
    id: '/api/admin/url-redirects/',
    path: '/api/admin/url-redirects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeIndexRoute = ApiAuthMeIndexRouteImport.update({
  id: '/api/auth/me/',
  path: '/api/auth/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeAvatarRoute = ApiAuthMeAvatarRouteImport.update({
  id: '/api/auth/me/avatar',
  path: '/api/auth/me/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMePasswordRoute = ApiAuthMePasswordRouteImport.update({
  id: '/api/auth/me/password',
  path: '/api/auth/me/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeSessionsRoute = ApiAuthMeSessionsRouteImport.update({
  id: '/api/auth/me/sessions',
  path: '/api/auth/me/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalUrlRedirectsIndexRoute =
  ApiInternalUrlRedirectsIndexRouteImport.update({
    id: '/api/internal/url-redirects/',
    path: '/api/internal/url-redirects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelV1DestinationsRoute = ApiTravelV1DestinationsRouteImport.update({
  id: '/api/travel/v1/destinations',
  path: '/api/travel/v1/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1FlightsRoute = ApiTravelV1FlightsRouteImport.update({
  id: '/api/travel/v1/flights',
  path: '/api/travel/v1/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1HotelsRoute = ApiTravelV1HotelsRouteImport.update({
  id: '/api/travel/v1/hotels',
  path: '/api/travel/v1/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelV1RecommendRoute = ApiTravelV1RecommendRouteImport.update({
  id: '/api/travel/v1/recommend',
  path: '/api/travel/v1/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPreferencesIndexRoute = ApiUserPreferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiUserPreferencesRoute,
} as any)
const ApiTravelV1DestinationsIndexRoute =
  ApiTravelV1DestinationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ApiTravelV1DestinationsRoute,
  } as any)
const ApiTravelV1DestinationsSlugRoute =
  ApiTravelV1DestinationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ApiTravelV1DestinationsRoute,
  } as any)
const ApiTravelV1DestinationsCountriesRoute =
  ApiTravelV1DestinationsCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => ApiTravelV1DestinationsRoute,
  } as any)
const ApiTravelV1FlightsIndexRoute = ApiTravelV1FlightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiTravelV1FlightsRoute,
} as any)
const ApiTravelV1HotelsIndexRoute = ApiTravelV1HotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiTravelV1HotelsRoute,
} as any)
const ApiTravelV1HotelsIdRoute = ApiTravelV1HotelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTravelV1HotelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/user/preferences': typeof ApiUserPreferencesRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/travel/v1/destinations': typeof ApiTravelV1DestinationsRouteWithChildren
  '/api/travel/v1/flights': typeof ApiTravelV1FlightsRouteWithChildren
  '/api/travel/v1/hotels': typeof ApiTravelV1HotelsRouteWithChildren
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/admin/url-redirects/': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me/': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects/': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences/': typeof ApiUserPreferencesIndexRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRoute
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRoute
  '/api/travel/v1/destinations/': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights/': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels/': typeof ApiTravelV1HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/admin/url-redirects': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences': typeof ApiUserPreferencesIndexRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRoute
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRoute
  '/api/travel/v1/destinations': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels': typeof ApiTravelV1HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/results': typeof ResultsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/robots': typeof ApiRobotsRoute
  '/api/sitemap': typeof ApiSitemapRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/legal/$pageType': typeof LegalPageTypeRoute
  '/preferences/edit': typeof PreferencesEditRoute
  '/preferences/quick': typeof PreferencesQuickRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/api/ai/preferences-insights': typeof ApiAiPreferencesInsightsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/health/ml-status': typeof ApiHealthMlStatusRoute
  '/api/internal/404-log': typeof ApiInternal404LogRoute
  '/api/user/preferences': typeof ApiUserPreferencesRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/auth/me/avatar': typeof ApiAuthMeAvatarRoute
  '/api/auth/me/password': typeof ApiAuthMePasswordRoute
  '/api/auth/me/sessions': typeof ApiAuthMeSessionsRoute
  '/api/travel/v1/destinations': typeof ApiTravelV1DestinationsRouteWithChildren
  '/api/travel/v1/flights': typeof ApiTravelV1FlightsRouteWithChildren
  '/api/travel/v1/hotels': typeof ApiTravelV1HotelsRouteWithChildren
  '/api/travel/v1/recommend': typeof ApiTravelV1RecommendRoute
  '/api/admin/url-redirects/': typeof ApiAdminUrlRedirectsIndexRoute
  '/api/auth/me/': typeof ApiAuthMeIndexRoute
  '/api/internal/url-redirects/': typeof ApiInternalUrlRedirectsIndexRoute
  '/api/user/preferences/': typeof ApiUserPreferencesIndexRoute
  '/api/travel/v1/destinations/$slug': typeof ApiTravelV1DestinationsSlugRoute
  '/api/travel/v1/destinations/countries': typeof ApiTravelV1DestinationsCountriesRoute
  '/api/travel/v1/hotels/$id': typeof ApiTravelV1HotelsIdRoute
  '/api/travel/v1/destinations/': typeof ApiTravelV1DestinationsIndexRoute
  '/api/travel/v1/flights/': typeof ApiTravelV1FlightsIndexRoute
  '/api/travel/v1/hotels/': typeof ApiTravelV1HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/health'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/ai/preferences-insights'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/user/preferences'
    | '/api/v1/$'
    | '/api/health/'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/travel/v1/destinations'
    | '/api/travel/v1/flights'
    | '/api/travel/v1/hotels'
    | '/api/travel/v1/recommend'
    | '/api/admin/url-redirects/'
    | '/api/auth/me/'
    | '/api/internal/url-redirects/'
    | '/api/user/preferences/'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/destinations/'
    | '/api/travel/v1/flights/'
    | '/api/travel/v1/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/ai/preferences-insights'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/v1/$'
    | '/api/health'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/travel/v1/recommend'
    | '/api/admin/url-redirects'
    | '/api/auth/me'
    | '/api/internal/url-redirects'
    | '/api/user/preferences'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/destinations'
    | '/api/travel/v1/flights'
    | '/api/travel/v1/hotels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/faq'
    | '/forgot-password'
    | '/preferences'
    | '/results'
    | '/api/contact'
    | '/api/health'
    | '/api/robots'
    | '/api/sitemap'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/destinations/$slug'
    | '/legal/$pageType'
    | '/preferences/edit'
    | '/preferences/quick'
    | '/roteiros/$slug'
    | '/api/ai/preferences-insights'
    | '/api/auth/$'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/health/ml-status'
    | '/api/internal/404-log'
    | '/api/user/preferences'
    | '/api/v1/$'
    | '/api/health/'
    | '/api/auth/me/avatar'
    | '/api/auth/me/password'
    | '/api/auth/me/sessions'
    | '/api/travel/v1/destinations'
    | '/api/travel/v1/flights'
    | '/api/travel/v1/hotels'
    | '/api/travel/v1/recommend'
    | '/api/admin/url-redirects/'
    | '/api/auth/me/'
    | '/api/internal/url-redirects/'
    | '/api/user/preferences/'
    | '/api/travel/v1/destinations/$slug'
    | '/api/travel/v1/destinations/countries'
    | '/api/travel/v1/hotels/$id'
    | '/api/travel/v1/destinations/'
    | '/api/travel/v1/flights/'
    | '/api/travel/v1/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PreferencesRoute: typeof PreferencesRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiRobotsRoute: typeof ApiRobotsRoute
  ApiSitemapRoute: typeof ApiSitemapRoute
  LegalPageTypeRoute: typeof LegalPageTypeRoute
  RoteirosSlugRoute: typeof RoteirosSlugRoute
  ApiAiPreferencesInsightsRoute: typeof ApiAiPreferencesInsightsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiInternal404LogRoute: typeof ApiInternal404LogRoute
  ApiUserPreferencesRoute: typeof ApiUserPreferencesRouteWithChildren
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiAuthMeAvatarRoute: typeof ApiAuthMeAvatarRoute
  ApiAuthMePasswordRoute: typeof ApiAuthMePasswordRoute
  ApiAuthMeSessionsRoute: typeof ApiAuthMeSessionsRoute
  ApiTravelV1DestinationsRoute: typeof ApiTravelV1DestinationsRouteWithChildren
  ApiTravelV1FlightsRoute: typeof ApiTravelV1FlightsRouteWithChildren
  ApiTravelV1HotelsRoute: typeof ApiTravelV1HotelsRouteWithChildren
  ApiTravelV1RecommendRoute: typeof ApiTravelV1RecommendRoute
  ApiAdminUrlRedirectsIndexRoute: typeof ApiAdminUrlRedirectsIndexRoute
  ApiAuthMeIndexRoute: typeof ApiAuthMeIndexRoute
  ApiInternalUrlRedirectsIndexRoute: typeof ApiInternalUrlRedirectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots': {
      id: '/api/robots'
      path: '/api/robots'
      fullPath: '/api/robots'
      preLoaderRoute: typeof ApiRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap': {
      id: '/api/sitemap'
      path: '/api/sitemap'
      fullPath: '/api/sitemap'
      preLoaderRoute: typeof ApiSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/legal/$pageType': {
      id: '/legal/$pageType'
      path: '/legal/$pageType'
      fullPath: '/legal/$pageType'
      preLoaderRoute: typeof LegalPageTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/edit': {
      id: '/preferences/edit'
      path: '/edit'
      fullPath: '/preferences/edit'
      preLoaderRoute: typeof PreferencesEditRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/preferences/quick': {
      id: '/preferences/quick'
      path: '/quick'
      fullPath: '/preferences/quick'
      preLoaderRoute: typeof PreferencesQuickRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/roteiros/$slug': {
      id: '/roteiros/$slug'
      path: '/roteiros/$slug'
      fullPath: '/roteiros/$slug'
      preLoaderRoute: typeof RoteirosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/preferences-insights': {
      id: '/api/ai/preferences-insights'
      path: '/api/ai/preferences-insights'
      fullPath: '/api/ai/preferences-insights'
      preLoaderRoute: typeof ApiAiPreferencesInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ml-status': {
      id: '/api/health/ml-status'
      path: '/ml-status'
      fullPath: '/api/health/ml-status'
      preLoaderRoute: typeof ApiHealthMlStatusRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/internal/404-log': {
      id: '/api/internal/404-log'
      path: '/api/internal/404-log'
      fullPath: '/api/internal/404-log'
      preLoaderRoute: typeof ApiInternal404LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences': {
      id: '/api/user/preferences'
      path: '/api/user/preferences'
      fullPath: '/api/user/preferences'
      preLoaderRoute: typeof ApiUserPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/url-redirects/': {
      id: '/api/admin/url-redirects/'
      path: '/api/admin/url-redirects'
      fullPath: '/api/admin/url-redirects/'
      preLoaderRoute: typeof ApiAdminUrlRedirectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/': {
      id: '/api/auth/me/'
      path: '/api/auth/me'
      fullPath: '/api/auth/me/'
      preLoaderRoute: typeof ApiAuthMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/avatar': {
      id: '/api/auth/me/avatar'
      path: '/api/auth/me/avatar'
      fullPath: '/api/auth/me/avatar'
      preLoaderRoute: typeof ApiAuthMeAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/password': {
      id: '/api/auth/me/password'
      path: '/api/auth/me/password'
      fullPath: '/api/auth/me/password'
      preLoaderRoute: typeof ApiAuthMePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me/sessions': {
      id: '/api/auth/me/sessions'
      path: '/api/auth/me/sessions'
      fullPath: '/api/auth/me/sessions'
      preLoaderRoute: typeof ApiAuthMeSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/url-redirects/': {
      id: '/api/internal/url-redirects/'
      path: '/api/internal/url-redirects'
      fullPath: '/api/internal/url-redirects/'
      preLoaderRoute: typeof ApiInternalUrlRedirectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/destinations': {
      id: '/api/travel/v1/destinations'
      path: '/api/travel/v1/destinations'
      fullPath: '/api/travel/v1/destinations'
      preLoaderRoute: typeof ApiTravelV1DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/flights': {
      id: '/api/travel/v1/flights'
      path: '/api/travel/v1/flights'
      fullPath: '/api/travel/v1/flights'
      preLoaderRoute: typeof ApiTravelV1FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/hotels': {
      id: '/api/travel/v1/hotels'
      path: '/api/travel/v1/hotels'
      fullPath: '/api/travel/v1/hotels'
      preLoaderRoute: typeof ApiTravelV1HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel/v1/recommend': {
      id: '/api/travel/v1/recommend'
      path: '/api/travel/v1/recommend'
      fullPath: '/api/travel/v1/recommend'
      preLoaderRoute: typeof ApiTravelV1RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/preferences/': {
      id: '/api/user/preferences/'
      path: '/'
      fullPath: '/api/user/preferences/'
      preLoaderRoute: typeof ApiUserPreferencesIndexRouteImport
      parentRoute: typeof ApiUserPreferencesRoute
    }
    '/api/travel/v1/destinations/': {
      id: '/api/travel/v1/destinations/'
      path: '/'
      fullPath: '/api/travel/v1/destinations/'
      preLoaderRoute: typeof ApiTravelV1DestinationsIndexRouteImport
      parentRoute: typeof ApiTravelV1DestinationsRoute
    }
    '/api/travel/v1/destinations/$slug': {
      id: '/api/travel/v1/destinations/$slug'
      path: '/$slug'
      fullPath: '/api/travel/v1/destinations/$slug'
      preLoaderRoute: typeof ApiTravelV1DestinationsSlugRouteImport
      parentRoute: typeof ApiTravelV1DestinationsRoute
    }
    '/api/travel/v1/destinations/countries': {
      id: '/api/travel/v1/destinations/countries'
      path: '/countries'
      fullPath: '/api/travel/v1/destinations/countries'
      preLoaderRoute: typeof ApiTravelV1DestinationsCountriesRouteImport
      parentRoute: typeof ApiTravelV1DestinationsRoute
    }
    '/api/travel/v1/flights/': {
      id: '/api/travel/v1/flights/'
      path: '/'
      fullPath: '/api/travel/v1/flights/'
      preLoaderRoute: typeof ApiTravelV1FlightsIndexRouteImport
      parentRoute: typeof ApiTravelV1FlightsRoute
    }
    '/api/travel/v1/hotels/': {
      id: '/api/travel/v1/hotels/'
      path: '/'
      fullPath: '/api/travel/v1/hotels/'
      preLoaderRoute: typeof ApiTravelV1HotelsIndexRouteImport
      parentRoute: typeof ApiTravelV1HotelsRoute
    }
    '/api/travel/v1/hotels/$id': {
      id: '/api/travel/v1/hotels/$id'
      path: '/$id'
      fullPath: '/api/travel/v1/hotels/$id'
      preLoaderRoute: typeof ApiTravelV1HotelsIdRouteImport
      parentRoute: typeof ApiTravelV1HotelsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface PreferencesRouteChildren {
  PreferencesEditRoute: typeof PreferencesEditRoute
  PreferencesQuickRoute: typeof PreferencesQuickRoute
}

const PreferencesRouteChildren: PreferencesRouteChildren = {
  PreferencesEditRoute: PreferencesEditRoute,
  PreferencesQuickRoute: PreferencesQuickRoute,
}

const PreferencesRouteWithChildren = PreferencesRoute._addFileChildren(
  PreferencesRouteChildren,
)

interface ApiHealthRouteChildren {
  ApiHealthMlStatusRoute: typeof ApiHealthMlStatusRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthMlStatusRoute: ApiHealthMlStatusRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiUserPreferencesRouteChildren {
  ApiUserPreferencesIndexRoute: typeof ApiUserPreferencesIndexRoute
}

const ApiUserPreferencesRouteChildren: ApiUserPreferencesRouteChildren = {
  ApiUserPreferencesIndexRoute: ApiUserPreferencesIndexRoute,
}

const ApiUserPreferencesRouteWithChildren =
  ApiUserPreferencesRoute._addFileChildren(ApiUserPreferencesRouteChildren)

interface ApiTravelV1DestinationsRouteChildren {
  ApiTravelV1DestinationsSlugRoute: typeof ApiTravelV1DestinationsSlugRoute
  ApiTravelV1DestinationsCountriesRoute: typeof ApiTravelV1DestinationsCountriesRoute
  ApiTravelV1DestinationsIndexRoute: typeof ApiTravelV1DestinationsIndexRoute
}

const ApiTravelV1DestinationsRouteChildren: ApiTravelV1DestinationsRouteChildren =
  {
    ApiTravelV1DestinationsSlugRoute: ApiTravelV1DestinationsSlugRoute,
    ApiTravelV1DestinationsCountriesRoute:
      ApiTravelV1DestinationsCountriesRoute,
    ApiTravelV1DestinationsIndexRoute: ApiTravelV1DestinationsIndexRoute,
  }

const ApiTravelV1DestinationsRouteWithChildren =
  ApiTravelV1DestinationsRoute._addFileChildren(
    ApiTravelV1DestinationsRouteChildren,
  )

interface ApiTravelV1FlightsRouteChildren {
  ApiTravelV1FlightsIndexRoute: typeof ApiTravelV1FlightsIndexRoute
}

const ApiTravelV1FlightsRouteChildren: ApiTravelV1FlightsRouteChildren = {
  ApiTravelV1FlightsIndexRoute: ApiTravelV1FlightsIndexRoute,
}

const ApiTravelV1FlightsRouteWithChildren =
  ApiTravelV1FlightsRoute._addFileChildren(ApiTravelV1FlightsRouteChildren)

interface ApiTravelV1HotelsRouteChildren {
  ApiTravelV1HotelsIdRoute: typeof ApiTravelV1HotelsIdRoute
  ApiTravelV1HotelsIndexRoute: typeof ApiTravelV1HotelsIndexRoute
}

const ApiTravelV1HotelsRouteChildren: ApiTravelV1HotelsRouteChildren = {
  ApiTravelV1HotelsIdRoute: ApiTravelV1HotelsIdRoute,
  ApiTravelV1HotelsIndexRoute: ApiTravelV1HotelsIndexRoute,
}

const ApiTravelV1HotelsRouteWithChildren =
  ApiTravelV1HotelsRoute._addFileChildren(ApiTravelV1HotelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PreferencesRoute: PreferencesRouteWithChildren,
  ResultsRoute: ResultsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiRobotsRoute: ApiRobotsRoute,
  ApiSitemapRoute: ApiSitemapRoute,
  LegalPageTypeRoute: LegalPageTypeRoute,
  RoteirosSlugRoute: RoteirosSlugRoute,
  ApiAiPreferencesInsightsRoute: ApiAiPreferencesInsightsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiInternal404LogRoute: ApiInternal404LogRoute,
  ApiUserPreferencesRoute: ApiUserPreferencesRouteWithChildren,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiAuthMeAvatarRoute: ApiAuthMeAvatarRoute,
  ApiAuthMePasswordRoute: ApiAuthMePasswordRoute,
  ApiAuthMeSessionsRoute: ApiAuthMeSessionsRoute,
  ApiTravelV1DestinationsRoute: ApiTravelV1DestinationsRouteWithChildren,
  ApiTravelV1FlightsRoute: ApiTravelV1FlightsRouteWithChildren,
  ApiTravelV1HotelsRoute: ApiTravelV1HotelsRouteWithChildren,
  ApiTravelV1RecommendRoute: ApiTravelV1RecommendRoute,
  ApiAdminUrlRedirectsIndexRoute: ApiAdminUrlRedirectsIndexRoute,
  ApiAuthMeIndexRoute: ApiAuthMeIndexRoute,
  ApiInternalUrlRedirectsIndexRoute: ApiInternalUrlRedirectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
