// packages/shared/src/types/ai-preferences/defaults.ts
import { THEME_TYPES } from '../../themes';
import { AIPreferences } from './interfaces';
import {
  TravelStyle,
  SustainabilityLevel,
  PersonalityType,
  ResponseLength,
  NotificationType,
  NotificationFrequency,
} from './enums';

export const DEFAULT_AI_PREFERENCES: AIPreferences = {
  openaiSecret: '',
  anthropicSecret: null,
  googleSecret: null,
  weatherApiKey: null,
  currencyApiKey: null,
  notifications: { email: true, push: true },
  temperature: 0.7,
  maxTokens: 2000,
  topP: 1,
  frequencyPenalty: 0,
  presencePenalty: 0,
  selectedModel: 'gpt-4-turbo-preview',
  interfaceSettings: {
    fontSize: 'medium',
    theme: THEME_TYPES.auto,
    language: 'pt',
    compactMode: false,
    showAdvancedOptions: false,
    enableKeyboardShortcuts: true,
    autoSave: true,
  },
  securitySettings: {
    twoFactorAuthEnabled: false,
    enableTwoFactor: false,
    sessionTimeout: 3600,
    requirePasswordForSensitiveActions: true,
    enableAuditLog: true,
    allowRememberDevice: true,
    encryptLocalData: false,
  },
  experimentalFeatures: {
    betaFeaturesEnabled: false,
    enableBetaFeatures: false,
    enableAdvancedAI: false,
    enableVoiceInput: false,
    enableRealTimeCollaboration: false,
    enablePredictiveSearch: false,
    enableSmartSuggestions: false,
  },
  modelParameters: {
    temperature: 0.7,
    maxTokens: 2000,
    topP: 1,
    frequencyPenalty: 0,
    presencePenalty: 0,
  },
  travelPreferences: {
    defaultBudgetRange: { min: 0, max: 10000, currency: 'EUR' },
    preferredTravelStyle: TravelStyle.Comfort,
    sustainabilityLevel: SustainabilityLevel.Medium,
    defaultTravelers: 1,
    preferredLanguages: ['pt', 'en'],
    preferredRegions: [],
    avoidCountries: [],
    preferredActivities: [],
    dietaryRestrictions: [],
    accessibilityNeeds: [],
    accommodationPreferences: ['hotel'],
    transportationPreferences: ['flight', 'train'],
    enableRealTimeData: true,
    enableWeatherIntegration: true,
    enableCurrencyConversion: true,
  },
  personalizationSettings: {
    personalityType: PersonalityType.Professional,
    responseLength: ResponseLength.Medium,
    includeLocalTips: true,
    includeBudgetBreakdown: true,
    includeAlternatives: true,
    includeWeatherInfo: true,
    includeCulturalInfo: true,
    includeHistoricalContext: true,
    preferDetailedItineraries: true,
    showPriceComparisons: true,
  },
  advancedSettings: {
    enableRealTimeData: true,
    enableWeatherIntegration: true,
    enableCurrencyConversion: true,
    cacheResponses: true,
    enableOfflineMode: false,
    autoSavePreferences: true,
    enableExperimentalFeatures: false,
    maxConcurrentRequests: 5,
    requestTimeout: 30000,
    retryAttempts: 3,
    enableAnalytics: true,
  },
  privacySettings: {
    participateInResearch: false,
    searchHistory: [],
    saveSearchHistory: true,
    shareDataForImprovement: false,
    allowPersonalization: true,
    enableLocationTracking: false,
    allowCookies: true,
    shareUsageStatistics: false,
    enableDataExport: true,
    autoDeleteHistoryAfter: 30,
    requireConsentForNewFeatures: true,
  },
  notificationSettings: {
    enabled: true,
    types: [NotificationType.Email, NotificationType.Push],
    frequency: NotificationFrequency.Daily,
    preferences: {
      tripSuggestions: true,
      priceAlerts: true,
      weatherUpdates: true,
      systemUpdates: true,
      marketingEmails: false,
    },
  },
  version: '1.0.0',
  lastUpdated: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
};
